version: "3"

services:
  api:
    image: demo-api
    build:
      context: .
    entrypoint: npm run watch
    environment:
      NODE_ENV: compose-dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/opt/app
